version: "3"

services:
  wiki:
    image: requarks/wiki:2.5
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: password # it's okay to have this in code since this is local DB
      DB_NAME: wiki
    ports:
    - ":3000"

  db:
    image: postgres:14.2
    environment:
      POSTGRES_DB: wiki
      POSTGRES_USER: wikijs
      POSTGRES_PASSWORD: password # it's okay to have this in code since this is local DB
    logging:
      driver: "none"
    volumes:
    - db-data:/var/lib/postgresql/data

volumes:
  db-data:
