version: "3"

services:
  wiki:
    image: requarks/wiki:2.5
    environment:
      DB_TYPE: postgres
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: password # it's okay to have this in code since this is local DB
      DB_NAME: wiki
    ports:
    - "3000:3000"
    logging:
      driver: "awslogs"
      options:
        awslogs-region: eu-west-1
        awslogs-group: chungcloudapps-documentation
        awslogs-stream-prefix: wiki

  db:
    image: postgres:14.2
    environment:
      POSTGRES_DB: wiki
      POSTGRES_USER: wikijs
      POSTGRES_PASSWORD: password # it's okay to have this in code since this is local DB
    logging:
      driver: "awslogs"
      options:
        awslogs-region: eu-west-1
        awslogs-group: chungcloudapps-documentaion
        awslogs-stream-prefix: db
    volumes:
    - db-data:/var/lib/postgresql/data

volumes:
  db-data:
